"""add comission

Revision ID: 5227d489a80f
Revises: 59206b022c77
Create Date: 2023-07-30 20:46:14.004398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5227d489a80f'
down_revision = '59206b022c77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comission', sa.Float(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.execute("UPDATE transactions SET comission = 0.0")
        batch_op.alter_column('comission', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('comission')

    # ### end Alembic commands ###
